### ISSUE TITLE
Plugin not Working

### ISSUE THREAD

**Issue by SirHardware** [streamyfin/jellyfin-plugin-streamyfin#10]
After Installing, rebooting Server, configuring and Logging in nothing happens.

#### Environment:
**Used Config;**
```
settings:
  downloadMethod:
    locked: true
    value: REMUX
  jellyseerrServerUrl:
    locked: true
    value: https://sub.domain.tld
```
**Jellyfin Version:** 10.10.3
**Plugin Version:** 0.32.0.0
**App Version:** it shows ``N/A`` (Android)
