### ISSUE TITLE
add support for collections or turn them off?

### ISSUE THREAD

**Issue by Simon-Eklundh** [streamyfin/jellyfin-plugin-streamyfin#18]
When using the following setting,

![Image](https://github.com/user-attachments/assets/13d8e3e6-6e5b-46f3-8e6d-94244fc196c0)

Streamyfin pulls collections into movies when includeItemTypes has movies
```yaml
- title: Recently Added Movies
        orientation: horizontal
        items:
          sortBy:
          - DateCreated
          sortOrder:
          - Descending
          includeItemTypes:
          - Movie
```

for example star gate:

![Image](https://github.com/user-attachments/assets/255b0d61-ed4b-4871-a05a-5bd9ab349b57)
which is a collection

## What should be done?

at a minimum: stop showing collections (just turn off the following option in the app api call)

![Image](https://github.com/user-attachments/assets/5a8faace-7d60-41d3-a207-767ffd5e7158)
preferably: give collections a poster

and possibly add collections as an option like 
![Image](https://github.com/user-attachments/assets/13d8e3e6-6e5b-46f3-8e6d-94244fc196c0)
