### ISSUE TITLE
Customizable Notification Messages

### ISSUE THREAD

**Issue by Dydhzo** [streamyfin/jellyfin-plugin-streamyfin#34]
# Feature Request: Customizable Notification Messages

## Description

Hi,
I would like to request the ability to customize the title and body of the notifications in the plugin. Currently, everything is set to English by default, and it is not possible to modify these fields directly within the plugin.

## Current Functionality

When using the webhook for notifications, we can already modify the content, but with the plugin, this is not possible. Here's an example of the current webhook format:
```json
[
    {
        {{#if_equals ItemType 'Movie'}}
          "title": "{{{Name}}} ({{Year}}) added",
          "body": "Watch movie now"
        {{/if_equals}}
        {{#if_equals ItemType 'Season'}}
          "title": "{{{SeriesName}}} season added",
          "body": "Watch season '{{{Name}}}' now"
        {{/if_equals}}
        {{#if_equals ItemType 'Episode'}}
          "title": "{{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} added",
          "body": "Watch episode '{{{Name}}}' now"
        {{/if_equals}}
    }
]
```
## Proposed Solution

I would like to have the ability to modify the title and body directly within the plugin, in a simple and user-friendly way. For example, the plugin could provide a configuration like this:
```yaml
notifications:
  itemAdded:
    enabled: true
    title: "{{{Name}}} ({{Year}}) added"
    body: "Watch the movie now"
  seasonAdded:
    enabled: true
    title: "{{{SeriesName}}} season added"
    body: "Watch season '{{{Name}}}' now"
  episodeAdded:
    enabled: true
    title: "{{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} added"
    body: "Watch episode '{{{Name}}}' now"
```

This would also be beneficial for notifications like these:
```yaml
  sessionStarted:
    enabled: true
  playbackStarted:
    enabled: true
  userLockedOut:
    enabled: true
```
## Benefits

This would allow users to customize the notification messages, including the title and body, to better fit their needs and language preferences.

Thank you for considering this feature!
